// Dashboard: loads profiles, ranks matches client-side, renders results.
let me = null;
let rankedMatches = [];
let currentSort = "score";
let cityScope = "city";
const FREE_MATCH_LIMIT = 6;
const PROFILE_FIELDS_FOR_COMPLETENESS = ["full_name","age","gender","mobile_number","city","preferred_area","budget_min","budget_max","sleep_schedule","cleanliness","guest_frequency","personality","smoking_drinking","cooking_habits","conflict_style","bio"];

document.addEventListener("DOMContentLoaded", async () => {
  const { data:{user} } = await supabaseClient.auth.getUser();
  if (!user) { location.href="login.html"; return; }
  const { data:myProfile } = await supabaseClient.from("profiles").select("*").eq("id",user.id).maybeSingle();
  if (!myProfile) { location.href="onboarding.html"; return; }
  if (await enforceActiveStatus(myProfile)) return;
  if (myProfile.is_admin) { location.href="admin.html"; return; }
  myProfile.is_premium = myProfile.is_premium===true || Boolean(myProfile.premium_since);
  me=myProfile;
  const welcome=document.getElementById("welcome-name"); if(welcome) welcome.textContent=myProfile.full_name?.split(" ")[0]||"there";
  document.getElementById("logout-btn")?.addEventListener("click",async e=>{e.preventDefault();await supabaseClient.auth.signOut();location.href="login.html";});
  document.getElementById("edit-profile-link")?.setAttribute("href","onboarding.html");
  renderCompleteness(); renderPremiumBanner(); wireCityScopeChip();
  document.querySelectorAll(".filter-chip[data-sort]").forEach(chip=>chip.addEventListener("click",()=>{document.querySelectorAll(".filter-chip[data-sort]").forEach(c=>c.classList.remove("active"));chip.classList.add("active");currentSort=chip.dataset.sort;renderSortedMatches();}));
  await Promise.all([loadMatches(),loadBroadcastBanner()]);
});

function renderPremiumBanner(){const b=document.getElementById("premium-banner"),badge=document.getElementById("premium-banner-badge"),title=document.getElementById("premium-banner-title"),sub=document.getElementById("premium-banner-sub"),btn=document.getElementById("premium-banner-btn");if(!b||!badge||!title||!sub||!btn)return;if(me.is_premium){b.classList.add("is-premium");badge.classList.add("is-premium");badge.textContent="✨ Premium active";title.textContent="You're on HomeSync AI Premium";sub.textContent="Unlimited matches, cross-city search, priority placement, and icebreakers are all unlocked.";btn.textContent="Manage plan";btn.href="pricing.html";}else{b.classList.remove("is-premium");badge.classList.remove("is-premium");badge.textContent="✨ Upgrade";title.textContent="HomeSync AI Premium";sub.textContent="Unlock priority matching, unlimited cross-city search and icebreaker suggestions.";btn.textContent="Upgrade to Premium";btn.href="pricing.html";}}
function wireCityScopeChip(){const chip=document.getElementById("city-scope-chip");if(!chip)return;if(!me.is_premium){chip.classList.add("upgrade-lock-chip");chip.textContent="🔒 All cities — Premium";chip.addEventListener("click",()=>location.href="pricing.html");return;}chip.textContent="📍 My city";chip.addEventListener("click",()=>{cityScope=cityScope==="city"?"all":"city";chip.textContent=cityScope==="city"?"📍 My city":"🌍 All cities";loadMatches();});}
const DISMISSED_BROADCAST_KEY="homesync-dismissed-broadcast";
async function loadBroadcastBanner(){const {data,error}=await supabaseClient.from("broadcasts").select("*").eq("is_active",true).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error||!data)return;let d=null;try{d=localStorage.getItem(DISMISSED_BROADCAST_KEY);}catch(e){}if(d===data.id)return;const b=document.getElementById("broadcast-banner");if(!b)return;document.getElementById("broadcast-banner-title").textContent=data.title;document.getElementById("broadcast-banner-body").textContent=data.body;b.classList.remove("hidden");document.getElementById("broadcast-banner-dismiss")?.addEventListener("click",()=>{b.classList.add("hidden");try{localStorage.setItem(DISMISSED_BROADCAST_KEY,data.id);}catch(e){}});}
function renderCompleteness(){const filled=PROFILE_FIELDS_FOR_COMPLETENESS.filter(f=>{const v=me[f];return v!==null&&v!==undefined&&String(v).trim()!=="";}).length;const pct=Math.round(filled/PROFILE_FIELDS_FOR_COMPLETENESS.length*100);const a=document.getElementById("stat-completeness");if(a)a.textContent=pct+"%";const c=document.getElementById("stat-city");if(c)c.textContent=me.city||"—";const h=document.getElementById("stat-completeness-hint");if(h){h.textContent=pct===100?"Fully filled out":"Finish it for stronger matches";h.classList.toggle("up",pct===100);}}

async function loadMatches(){const list=document.getElementById("match-list");if(!list)return;list.innerHTML=skeletonHtml(3);let q=supabaseClient.from("profiles").select("*").neq("id",me.id);if(me.city)q=q.eq("city",me.city);const {data:localCandidates,error}=await q;if(error){list.innerHTML=`<div class="card empty-state"><div class="empty-state-icon">⚠️</div><p class="muted">Couldn't load matches: ${escapeHtml(error.message)}</p></div>`;setStatFallback();return;}let candidates=[...(localCandidates||[])];if(me.is_premium&&cityScope==="all"){const {data:all}=await supabaseClient.from("profiles").select("*").neq("id",me.id);if(all){const seen=new Set(candidates.map(p=>p.id));all.forEach(p=>{if(!seen.has(p.id)){candidates.push(p);seen.add(p.id);}});}}
  if(!candidates.length){list.innerHTML=`<div class="card empty-state"><div class="empty-state-icon">🏠</div><p class="muted">No other profiles found in ${escapeHtml(me.city||"your city")} yet.</p></div>`;setStatFallback();return;}
  candidates.forEach(p=>p.is_premium=p.is_premium===true||Boolean(p.premium_since));
  rankedMatches=rankMatches(me,candidates,me.is_premium?candidates.length:20).map(m=>({...m,displayScore:m.ruleScore}));
  if(!rankedMatches.length){list.innerHTML=`<div class="card empty-state"><div class="empty-state-icon">🤷</div><p class="muted">No compatible matches found yet.</p></div>`;setStatFallback();return;}
  rankedMatches.sort((a,b)=>b.ruleScore-a.ruleScore);
  document.getElementById("stat-match-count")?.replaceChildren(document.createTextNode(String(rankedMatches.length)));
  document.getElementById("stat-top-score")?.replaceChildren(document.createTextNode(Math.round(rankedMatches[0].ruleScore)+"%"));
  renderSortedMatches();
}
function setStatFallback(){document.getElementById("stat-match-count")?.replaceChildren(document.createTextNode("0"));document.getElementById("stat-top-score")?.replaceChildren(document.createTextNode("—"));}
function renderSortedMatches(){const list=document.getElementById("match-list");if(!list)return;const sorted=[...rankedMatches];if(currentSort==="budget")sorted.sort((a,b)=>(a.profile.budget_min??Infinity)-(b.profile.budget_min??Infinity));else sorted.sort((a,b)=>b.ruleScore-a.ruleScore);list.innerHTML="";const limit=me.is_premium?sorted.length:FREE_MATCH_LIMIT;sorted.slice(0,limit).forEach((m,i)=>renderMatchCard(list,m,i===0));const locked=sorted.length-limit;if(locked>0)renderLockedMatchTeaser(list,locked);}
function renderLockedMatchTeaser(list,n){const w=document.createElement("div");w.className="locked-match-card";w.innerHTML=`<div class="locked-match-card-cta"><span>🔒</span><strong>${n} more matches</strong><a href="pricing.html" class="btn btn-primary">Unlock unlimited matches</a></div>`;list.appendChild(w);}
function skeletonHtml(n){return Array.from({length:n},()=>`<div class="skeleton-card"><div class="skeleton skeleton-circle"></div><div><div class="skeleton skeleton-line" style="width:40%"></div><div class="skeleton skeleton-line" style="width:70%"></div><div class="skeleton skeleton-line" style="width:55%"></div></div></div>`).join("");}
function renderMatchCard(list,match,isTop){const {profile,ruleScore,breakdown}=match;const card=document.createElement("div");card.className="card match-card"+(isTop?" top-vibe-match":"");const dial=document.createElement("div");dial.className="mini-dial";const info=document.createElement("div");const avatar=profile.photo_url?`background-image:url(${escapeAttr(profile.photo_url)});`: `background:${avatarColor(profile.id)};`;const badge=isTop?`<div class="best-vibe-badge">🏆 Best vibe match</div>`:"";const view=`<a class="btn-contact" href="public-profile.html?id=${encodeURIComponent(profile.id)}">👤 View profile</a>`;info.innerHTML=`${badge}<div class="match-header-row"><div class="match-avatar" style="${avatar}">${profile.photo_url?"":initials(profile.full_name)}</div><div class="match-name">${escapeHtml(profile.full_name||"Unnamed")}</div>${profile.is_premium?`<span class="match-priority-tag">⭐ Premium</span>`:""}</div><p class="muted">${escapeHtml(profile.preferred_area||profile.city||"")} · ₹${profile.budget_min||"?"}–₹${profile.budget_max||"?"}</p><p>${escapeHtml((profile.bio||"").slice(0,180))}</p><div class="score-breakdown"><span>Lifestyle ${Math.round(ruleScore)}%</span><span>Sleep ${pct(breakdown.sleep_schedule)}</span><span>Clean ${pct(breakdown.cleanliness)}</span><span>Social ${pct(breakdown.guest_frequency)}</span></div><div class="contact-row">${view}${renderContactRow(profile)}</div>${renderIcebreakerButton(profile)}<div class="icebreaker-box hidden" id="icebreaker-${escapeAttr(profile.id)}"></div>`;card.append(dial,info,document.createElement("div"));list.appendChild(card);renderSyncDial(dial,ruleScore,{size:78,label:""});info.querySelector("[data-action='icebreaker']")?.addEventListener("click",()=>handleIcebreakerClick(profile));}
function renderIcebreakerButton(profile){return me.is_premium?`<button type="button" class="btn-icebreaker" data-action="icebreaker" style="margin-top:12px">✨ Suggest an icebreaker</button>`:`<button type="button" class="btn-icebreaker locked" data-action="icebreaker" style="margin-top:12px">🔒 Icebreaker — Premium</button>`;}
function handleIcebreakerClick(profile){if(!me.is_premium){location.href="pricing.html";return;}const box=document.getElementById(`icebreaker-${profile.id}`);if(!box)return;if(!box.classList.contains("hidden")){box.classList.add("hidden");return;}const text=generateIcebreaker(me,profile);box.innerHTML=`<p>${escapeHtml(text)}</p><button type="button" class="btn-icebreaker" data-copy>📋 Copy</button>`;box.classList.remove("hidden");box.querySelector("[data-copy]")?.addEventListener("click",e=>{navigator.clipboard?.writeText(text);e.currentTarget.textContent="Copied ✓";});}
function generateIcebreaker(me,profile){const name=(profile.full_name||"there").split(" ")[0];return `Hey ${name}! We matched pretty high on HomeSync — want to compare notes on the flat hunt and see if it's worth meeting?`;}
function renderContactRow(profile){const b=[];if(profile.email)b.push(`<a class="btn-contact" href="mailto:${escapeAttr(profile.email)}">✉️ Email</a>`);if(profile.mobile_number){const d=profile.mobile_number.replace(/\D/g,"");const n=d.length===10?"91"+d:d;b.push(`<a class="btn-contact whatsapp" target="_blank" rel="noopener" href="https://wa.me/${n}">💬 WhatsApp</a>`);}return b.join("");}
function escapeAttr(s){return String(s||"").replace(/"/g,"&quot;");}function pct(s){return Math.round((s??0)*100)+"%";}function escapeHtml(s){const d=document.createElement("div");d.textContent=s||"";return d.innerHTML;}
