// HomeSync compatibility scoring engine.
// Lifestyle is the source of truth for the primary match ranking.
// Practical constraints (budget/location) are surfaced separately instead of
// silently deleting a potentially excellent lifestyle match.
const WEIGHTS={sleep_schedule:.20,cleanliness:.22,guest_frequency:.12,personality:.14,smoking_drinking:.14,cooking_habits:.10,conflict_style:.08};
const QUESTION_WEIGHTS={sleep_time:.10,wake_time:.07,study_work_schedule:.05,clean_room:.10,dishes:.06,shared_cleaning:.05,guest_frequency:.08,social_energy:.06,noise_conflict:.07,smoking_home:.10,cooking_frequency:.06,personal_space:.06,move_in_timing:.05,commute_priority:.05,verification_priority:.04};
const CATEGORICAL_TABLES={smoking_drinking:{never:{never:1,social:.55,regular:.15},social:{never:.55,social:1,regular:.6},regular:{never:.15,social:.6,regular:1}},cooking_habits:{self_cook:{self_cook:1,order_in:.5,shared:.75},order_in:{self_cook:.5,order_in:1,shared:.6},shared:{self_cook:.75,order_in:.6,shared:1}},conflict_style:{avoids:{avoids:.7,discusses:.55,confronts:.25},discusses:{avoids:.55,discusses:1,confronts:.65},confronts:{avoids:.25,discusses:.65,confronts:.7}}};
function simNumeric(a,b,max=5){if(a==null||b==null)return .5;return 1-Math.abs(Number(a)-Number(b))/(max-1)}
function simCategorical(field,a,b){if(!a||!b)return .5;const t=CATEGORICAL_TABLES[field];return t?t[a]?.[b]??.3:(a===b?1:.3)}
function budgetOverlaps(a,b){if(a.budget_min==null||a.budget_max==null||b.budget_min==null||b.budget_max==null)return true;return a.budget_min<=b.budget_max&&b.budget_min<=a.budget_max}
function budgetSimilarity(a,b){if(!budgetOverlaps(a,b))return 0;const amin=Number(a.budget_min),amax=Number(a.budget_max),bmin=Number(b.budget_min),bmax=Number(b.budget_max);const midA=(amin+amax)/2,midB=(bmin+bmax)/2;const scale=Math.max(midA,midB,1);return Math.max(0,1-Math.abs(midA-midB)/scale)}
function questionnaireSimilarity(a,b){const aa=a.compatibility_answers,bb=b.compatibility_answers;if(!aa||!bb||typeof aa!=='object'||typeof bb!=='object')return null;const keys=Object.keys(QUESTION_WEIGHTS),available=keys.filter(k=>aa[k]!=null&&bb[k]!=null);if(available.length<8)return null;const da=Array.isArray(a.compatibility_dealbreakers)?a.compatibility_dealbreakers:[],db=Array.isArray(b.compatibility_dealbreakers)?b.compatibility_dealbreakers:[],dealbreakers=new Set([...da,...db]);for(const key of dealbreakers)if(aa[key]!=null&&bb[key]!=null&&Number(aa[key])!==Number(bb[key]))return null;let weighted=0,total=0;const details={};for(const key of available){const similarity=1-Math.abs(Number(aa[key])-Number(bb[key]))/3,weight=QUESTION_WEIGHTS[key];weighted+=weight*similarity;total+=weight;details[key]=similarity}return{score:total?weighted/total:.5,details,matchedQuestions:available.length,totalQuestions:keys.length}}
function legacyRuleScore(a,b){const breakdown={sleep_schedule:simNumeric(a.sleep_schedule,b.sleep_schedule),cleanliness:simNumeric(a.cleanliness,b.cleanliness),guest_frequency:simNumeric(a.guest_frequency,b.guest_frequency),personality:simNumeric(a.personality,b.personality),smoking_drinking:simCategorical('smoking_drinking',a.smoking_drinking,b.smoking_drinking),cooking_habits:simCategorical('cooking_habits',a.cooking_habits,b.cooking_habits),conflict_style:simCategorical('conflict_style',a.conflict_style,b.conflict_style)};let score=0;for(const k in WEIGHTS)score+=WEIGHTS[k]*(breakdown[k]??.5);return{score,breakdown,source:'legacy'}}
function computeRuleScore(a,b){const questionnaire=questionnaireSimilarity(a,b);if(questionnaire){const d=questionnaire.details;return{score:Math.round(questionnaire.score*100),breakdown:{sleep_schedule:d.sleep_time??.5,cleanliness:d.clean_room??.5,guest_frequency:d.guest_frequency??.5,personality:d.social_energy??.5,smoking_drinking:d.smoking_home??.5,cooking_habits:d.cooking_frequency??.5,conflict_style:d.noise_conflict??.5,...d},source:'15-question-lifestyle',matchedQuestions:questionnaire.matchedQuestions,totalQuestions:questionnaire.totalQuestions,budgetCompatible:budgetOverlaps(a,b),budgetScore:Math.round(budgetSimilarity(a,b)*100)}}const legacy=legacyRuleScore(a,b);return{score:Math.round(legacy.score*100),breakdown:legacy.breakdown,source:legacy.source,budgetCompatible:budgetOverlaps(a,b),budgetScore:Math.round(budgetSimilarity(a,b)*100)}}
function computeHybridScore(ruleScore,llmScore,alpha=.6){if(llmScore==null)return ruleScore;return Math.round(alpha*ruleScore+(1-alpha)*llmScore)}
function rankMatches(me,candidates,topN=20){return candidates.map(c=>{const r=computeRuleScore(me,c);return{profile:c,ruleScore:r.score,breakdown:r.breakdown,scoreSource:r.source,matchedQuestions:r.matchedQuestions,totalQuestions:r.totalQuestions,budgetCompatible:r.budgetCompatible,budgetScore:r.budgetScore}}).sort((a,b)=>b.ruleScore-a.ruleScore).slice(0,topN)}
