let user, conversation, session, map, meMarker, otherMarker, watchId=null, realtime=null, lastLocation=null;
document.addEventListener('DOMContentLoaded', init);
async function init(){
 const {data:{user:u}}=await supabaseClient.auth.getUser(); if(!u){location.href='login.html';return;} user=u;
 const cid=new URLSearchParams(location.search).get('conversation_id'); if(!cid){fail('No accepted conversation was selected.');return;}
 const {data:c,error}=await supabaseClient.from('conversations').select('*').eq('id',cid).maybeSingle(); if(error||!c){fail('This private conversation is unavailable.');return;} conversation=c;
 const otherId=c.participant_a===user.id?c.participant_b:c.participant_a;
 const {data:p}=await supabaseClient.from('profiles').select('full_name,city,preferred_area').eq('id',otherId).maybeSingle();
 document.getElementById('person-title').textContent=`Safe visit with ${p?.full_name||'your match'}`;document.getElementById('person-sub').textContent=`${p?.preferred_area||p?.city||'Accepted HomeSync match'} · location sharing is opt-in`;
 initMap(); await loadExisting(); subscribe();
 document.getElementById('locate-btn').onclick=locateMe;document.getElementById('share-btn').onclick=toggleSharing;document.getElementById('save-destination').onclick=saveDestination;document.getElementById('checkin-btn').onclick=checkIn;document.getElementById('complete-btn').onclick=endVisit;document.getElementById('maps-btn').onclick=openNavigation;
}
function initMap(){map=L.map('visit-map').setView([28.6139,77.209],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);}
async function loadExisting(){const {data}=await supabaseClient.from('safe_visit_sessions').select('*').eq('conversation_id',conversation.id).in('status',['planned','active']).order('created_at',{ascending:false}).limit(1).maybeSingle();if(data){session=data;document.getElementById('destination-label').value=data.destination_label||'';document.getElementById('destination-lat').value=data.destination_latitude||'';document.getElementById('destination-lng').value=data.destination_longitude||'';setStatus(data.status==='active'?'Visit active · live sharing is controlled by consent':'Visit planned');if(data.destination_latitude&&data.destination_longitude)showDestination(data.destination_latitude,data.destination_longitude);}}
async function createOrGetSession(){if(session)return session;const host=conversation.participant_a===user.id?conversation.participant_b:conversation.participant_a;const visitor=user.id;const {data,error}=await supabaseClient.from('safe_visit_sessions').insert({conversation_id:conversation.id,host_id:host,visitor_id:visitor,status:'planned'}).select().single();if(error)throw error;session=data;return session;}
async function saveDestination(){try{await createOrGetSession();const lat=parseFloat(document.getElementById('destination-lat').value),lng=parseFloat(document.getElementById('destination-lng').value),label=document.getElementById('destination-label').value.trim();if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('Enter valid destination coordinates.');const {error}=await supabaseClient.from('safe_visit_sessions').update({destination_label:label||'Meeting location',destination_latitude:lat,destination_longitude:lng}).eq('id',session.id);if(error)throw error;session.destination_latitude=lat;session.destination_longitude=lng;session.destination_label=label;showDestination(lat,lng);setStatus('Destination saved.');}catch(e){alert(e.message);}}
async function toggleSharing(){try{await createOrGetSession();const next=!session.share_enabled;const update={share_enabled:next,status:next?'active':session.status,started_at:next&&!session.started_at?new Date().toISOString():session.started_at};const {error}=await supabaseClient.from('safe_visit_sessions').update(update).eq('id',session.id);if(error)throw error;session={...session,...update};if(next){document.getElementById('share-btn').textContent='🛑 Stop live sharing';setStatus('Live location sharing ON');startLocationWatch();}else{document.getElementById('share-btn').textContent='🔒 Enable live sharing';setStatus('Live location sharing OFF');stopLocationWatch();}}catch(e){alert(e.message);}}
function startLocationWatch(){if(!navigator.geolocation){alert('Location is not supported by this browser.');return;}if(watchId!==null)return;watchId=navigator.geolocation.watchPosition(async pos=>{lastLocation=pos;setMeMarker(pos.coords.latitude,pos.coords.longitude);await supabaseClient.from('live_visit_locations').insert({session_id:session.id,user_id:user.id,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy_meters:pos.coords.accuracy});},{enableHighAccuracy:true,maximumAge:5000,timeout:10000});}
function stopLocationWatch(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;}}
function locateMe(){if(!navigator.geolocation)return alert('Location is not supported.');navigator.geolocation.getCurrentPosition(pos=>{setMeMarker(pos.coords.latitude,pos.coords.longitude);map.setView([pos.coords.latitude,pos.coords.longitude],16);},()=>alert('Location permission was not granted.'),{enableHighAccuracy:true});}
async function checkIn(){if(!session)await createOrGetSession();const {error}=await supabaseClient.from('safe_visit_sessions').update({status:'active',checkin_at:new Date().toISOString()}).eq('id',session.id);if(error)alert(error.message);else{session.status='active';setStatus('✓ Safety check-in recorded');await notifyOther('safe_visit_checkin','Your HomeSync match checked in safely during a visit.');}}
async function endVisit(){if(!session)return;stopLocationWatch();const {error}=await supabaseClient.from('safe_visit_sessions').update({status:'completed',completed_at:new Date().toISOString(),share_enabled:false}).eq('id',session.id);if(error)alert(error.message);else{session.status='completed';setStatus('Visit completed · live sharing stopped');await notifyOther('safe_visit_completed','The HomeSync safe visit has ended.');}}
async function notifyOther(type,body){const otherId=conversation.participant_a===user.id?conversation.participant_b:conversation.participant_a;await supabaseClient.from('notifications').insert({user_id:otherId,type,title:type==='safe_visit_checkin'?'Safe visit check-in':'Safe visit completed',body,data:{conversation_id:conversation.id,visit_session_id:session.id}});}
function subscribe(){realtime=supabaseClient.channel(`visit:${conversation.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'live_visit_locations'},async payload=>{if(!session||payload.new.session_id!==session.id||payload.new.user_id===user.id)return;setOtherMarker(payload.new.latitude,payload.new.longitude);}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'safe_visit_sessions',filter:`id=eq.${session?.id||'00000000-0000-0000-0000-000000000000'}`},payload=>{session={...session,...payload.new};}).subscribe();}
function showDestination(lat,lng){if(!window.L)return;L.marker([lat,lng]).addTo(map).bindPopup('Meeting / room location').openPopup();map.setView([lat,lng],15);}
function setMeMarker(lat,lng){if(meMarker)meMarker.setLatLng([lat,lng]);else meMarker=L.circleMarker([lat,lng],{radius:9,color:'#10b981',fillColor:'#10b981',fillOpacity:.9}).addTo(map).bindPopup('Your live location');}
function setOtherMarker(lat,lng){if(otherMarker)otherMarker.setLatLng([lat,lng]);else otherMarker=L.circleMarker([lat,lng],{radius:9,color:'#3b82f6',fillColor:'#3b82f6',fillOpacity:.9}).addTo(map).bindPopup('Match location');}
function openNavigation(){const lat=parseFloat(document.getElementById('destination-lat').value),lng=parseFloat(document.getElementById('destination-lng').value);if(!Number.isFinite(lat)||!Number.isFinite(lng)){alert('Save a destination first.');return;}const origin=lastLocation?`${lastLocation.coords.latitude},${lastLocation.coords.longitude}`:'';window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${lat},${lng}&travelmode=driving`,'_blank','noopener');}
function setStatus(s){document.getElementById('status').innerHTML=`<span class="live-dot"></span><strong>${esc(s)}</strong>`;}function fail(s){document.body.innerHTML=`<main class="wrap section-tight"><div class="card"><h2>Safe visit unavailable</h2><p class="muted">${esc(s)}</p><a class="btn btn-primary" href="chat.html">Back to chat</a></div></main>`;}function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
