// Global HomeSync dark/light theme. Persisted across the entire app.
const THEME_KEY = "homesync-theme";
function getStoredTheme(){try{return localStorage.getItem(THEME_KEY)}catch(e){return null}}
function setStoredTheme(theme){try{localStorage.setItem(THEME_KEY,theme)}catch(e){}}
function applyTheme(theme){document.body.classList.toggle("light",theme==="light");document.querySelectorAll(".theme-toggle").forEach(btn=>{btn.setAttribute("aria-label",theme==="light"?"Switch to dark mode":"Switch to light mode");btn.title=theme==="light"?"Dark mode":"Light mode";btn.innerHTML=theme==="light"?"☀️":"🌙";});}
function toggleTheme(){const next=document.body.classList.contains("light")?"dark":"light";applyTheme(next);setStoredTheme(next);}
function ensureThemeControl(){if(document.querySelector(".theme-toggle"))return;const b=document.createElement("button");b.type="button";b.className="theme-toggle hs-global-theme-toggle";b.setAttribute("aria-label","Switch to light mode");b.title="Light mode";b.innerHTML="🌙";b.addEventListener("click",toggleTheme);document.body.appendChild(b);const s=document.createElement("style");s.textContent='.hs-global-theme-toggle{position:fixed;right:18px;bottom:18px;z-index:1000;width:44px;height:44px;border-radius:50%;border:1px solid var(--line);background:var(--canvas-raised);color:var(--ink);box-shadow:0 10px 28px rgba(0,0,0,.18);cursor:pointer;font-size:18px}.hs-global-theme-toggle:hover{transform:translateY(-1px);border-color:var(--plum)}';document.head.appendChild(s);}
function initTheme(){const stored=getStoredTheme()||"dark";applyTheme(stored);ensureThemeControl();document.querySelectorAll(".theme-toggle").forEach(btn=>{btn.addEventListener("click",toggleTheme);});}
function initMobileNav(){const toggle=document.getElementById("nav-toggle"),links=document.getElementById("nav-links");if(!toggle||!links)return;const close=()=>{links.classList.remove("open");toggle.setAttribute("aria-expanded","false")};toggle.addEventListener("click",()=>{const open=links.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open));});links.querySelectorAll("a,button:not(#nav-toggle)").forEach(el=>el.addEventListener("click",close));document.addEventListener("click",e=>{if(links.classList.contains("open")&&!links.contains(e.target)&&!toggle.contains(e.target))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});}
document.addEventListener("DOMContentLoaded",initTheme);document.addEventListener("DOMContentLoaded",initMobileNav);